services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    command: yarn run start:dev
    ports:
      - 3000:3000
    volumes:
      - ./packages/backend/node_modules:/app/node_modules
      - ./packages/backend/:/app
    env_file:
      - ./packages/backend/.env
    depends_on:
      - database

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    command: yarn run dev
    ports:
      - 3001:5173
    volumes:
      - ./packages/frontend/node_modules:/app/node_modules
      - ./packages/frontend/:/app
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

  database:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=crudtarefas
